name: Linting

on:
  push:
    paths:
      - "**.php"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: './app'
          ignore: './vendor/\*\;./tests/\*'
