name: Linting

on:
  push:
    paths:
      - "**.php"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: overtrue/phplint@7.4
        with:
          path: .
          options: --exclude=vendor

      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: './app'
          ignore: './vendor/\*\;./tests/\*'
