name: Linting

on:
  push:
    # paths:
    #   - "**.php"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4','8.0']
  
    steps:
      - uses: actions/checkout@v2
      - uses: overtrue/phplint@${{ matrix.php-version }}
      - uses: MilesChou/php-tools-action/${{ matrix.php-version }}/phpcs@master
      - uses: MilesChou/php-tools-action/${{ matrix.php-version }}/phpmd@master
