name: Linting

on:
  push:
    paths:
      - "**"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.4
      with:
        dir: './app'